### ISSUE TITLE
Possible issue with IR generation

### ISSUE THREAD

**Issue by mayanksolanki393** [CS639A-PAVT/BugTracker#1]
---
name: Bug report
about: Intermediate Representation
title:  Possible issue with IR generation
labels: bug
assignees: skmuduli92

---

**Describe the bug**
The IR is not skipping the else block in an if-else statement. Please take a look at the screenshots for details.
I believe this is causing an issue in the interpreter as well.

**To Reproduce**
program:
```
:radius = 1
:flag = 1
	
repeat 20 [
		
	if (:flag == 1) [
		repeat 36 [
			forward :radius
			left 10
		]
		:flag = 0
	] else [
		repeat 36 [
			forward :radius
			right 10
		]
		:flag = 1
	]
	
	:radius = :radius + 2
	
]
```

**Screenshots**
![issue](https://user-images.githubusercontent.com/10232424/131342614-900094e0-6b32-48f3-a628-cc9b191e7760.JPG)

![programexecution](https://user-images.githubusercontent.com/10232424/131342616-ec4aa88e-391a-42c8-8edd-d18cec4e15fa.JPG)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - Python3 version Python 3.8.10
 - Any other dependencies

**Comment by skmuduli92** [comment]
@mayanksolanki393 Thanks for reporting this issue. I am looking into it, will get back to you soon.
