### ISSUE TITLE
testData is not converted to dictionary properly.

### ISSUE THREAD

**Issue by Malkeet-dhalla** [CS639A-PAVT/BugTracker#16]
**Describe the bug**
Line 47 in `sExecutionInterface.py` is  `symbEnc = convertExp(None,testData[tests]["symbEnc"])`. Shouldn't it be `testData[tests]["symbEnc"] = convertExp(None,testData[tests]["symbEnc"])`?

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python 3.8
 - Kachua v3.2

**Comment by tgourav** [comment]
Thanks, fixed in release Kachua v3.3.
