### ISSUE TITLE
Error in symbolic execution if no conditional statement is present in the program

### ISSUE THREAD

**Issue by Malkeet-dhalla** [CS639A-PAVT/BugTracker#17]
**Describe the bug**
In `symbolicExecutionMain` function in `sExecution.py`, `pc` remains empty if no `kachuaAST.ConditionCommand` is present in the ir and line 35 tries to index this empty `pc`.

**To Reproduce**
test.tl
`:x = :x + :c1`

Executing `./kachua.py -t 10 -se test.tl -d '{":x": 1}' -c '{":c1": 1}'` gives this error
![Screenshot from 2021-10-20 19-34-02](https://user-images.githubusercontent.com/57011167/138108397-73abee5f-8b68-4d23-848e-ada75e387cd9.png)

**Desktop**
 - OS: Ubuntu 20.04
 - Python 3.8
 - Kachua v3.3

**Comment by tgourav** [comment]
Fix for this bug added in release Kachua v3.4
