### ISSUE TITLE
Kachua is not using the optimized IR

### ISSUE THREAD

**Issue by mayanksolanki393** [CS639A-PAVT/BugTracker#2]
---
name: Bug report
about: Kachua Interpreter
title: 'Kachua is not using the optimized IR'
labels: bug
assignees: skmuduli92

---

**Describe the bug**
Kindly refer the screenshot

**To Reproduce**
1. create kachua program and submission.py using the following code
- kachua program
```
forward 20
forward 30
```
- submission.py 
```
#leave other function as-is
def optimize(ir):
    # create optimized ir by using only the first statement and discarding the second statement
    ir2 = [ir[0]]
    print("len(ir2)", len(ir2))
    print("new ir:", ir2[0][0])
    return ir2
```
2. from the KachuaCore directory, execute 
> python .\kachua.py -r -O "path-to-kachua-program"

**Screenshots**
![bug](https://user-images.githubusercontent.com/10232424/133737082-3b2674f1-6ac5-4d92-bbc9-805f586e4310.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python3 version: Python 3.8.5

**Comment by lahiri-phdworks** [comment]
Yes, this is an issue. In `kachua.py`, can you try this.

```python3
    if args.opt:
        ir2 = optimize(ir)
        ir = ir2
        dumpIR("optimized.kw", ir)
```

**Comment by mayanksolanki393** [comment]
This would work as we are not optimizing the IR. Actually, this is an issue is related to assignment #3. If I optimize the IR and execute it. The interpreter still used the original IR and not the optimized one. So, I am not able to check if the optimized IR is generating the same figure or not.

**Comment by mayanksolanki393** [comment]
Sorry, I did not read your comment correctly. I will give your approach a try and get back.

**Comment by mayanksolanki393** [comment]
yes, it is working. Thank you.

Please let me know how to incorporate this into the assignment. Should I add a comment in the readme or it would be fixed in a new version.

**Comment by lahiri-phdworks** [comment]
We will add to the next release. Thanks for informing.
