### ISSUE TITLE
Spectrum Based Fault Localization

### ISSUE THREAD

**Issue by Harsh30199** [CS639A-PAVT/BugTracker#21]
In sbfl.py, there is a function selBest() which to best of my understanding should sort the population based on fitness score in descending order while code is currently doing in ascending order. PLs check

 def selBest(self, population, k):
        """
        This function selects best k individuals from population.
        if |population| > k, then best k individuals are returned in 
        sorted order
        ----------
        population : list of Individuals
            list of individual from where best-k individuals will be selected.
        k : int
            number of best individuals to return.
        Returns
        -------
        list
        """
        #temp contains : fitnes value, test case size, index of individual in population
        temp = []
        for i,ind in enumerate(population):
            temp.append([ind.fitness,len(ind.individual),i])
        **temp = sorted(temp,reverse=False) #####ToDo : Fix it to generic way**
        
        if len(temp) >=k:
            return [population[i[2]] for i in temp[:k]]
        else:
            return [population[i[2]] for i in temp]

**Comment by Vishalsng112** [comment]
@Harsh30199, yes the function **selBest()** sorts the population based on fitness score in ascending order. the framework is designed in that way.
Our assumption is lower fitness-score means test-suite is better. for example suppose we have two test-suite t1 and t2 and fitness(t1) = 0.1 and fitness(t2) = 0.3 then test-suite t1 is better. that is why it is sorted in ascending order.

while designing your fitness function if your assumption is  that greater fitness-score means better test-suite then I would suggest you return **(-fitness_score)**.
