### ISSUE TITLE
[SBFL] Circular imports

### ISSUE THREAD

**Issue by Malkeet-dhalla** [CS639A-PAVT/BugTracker#22]
**Describe the bug**
There's a circular dependency between `sbfl.py` and `sbflSubmission.py`.  This does not cause any problem in running sbfl but using pytest gives an `ImportError`. You can safely remove `from sbfl import *` line from `sbflSubmission.py` as we do not need anything from that module.

**Desktop**
 - OS: EndeavourOS
 - Python 3.9

**Comment by Malkeet-dhalla** [comment]
Also, Why does `kachua.py` uses `python3.8` in shebang? I have only python 3.9 installed so using `./kachua.py` gives me an error.

**Comment by skmuduli92** [comment]
@Malkeet-dhalla Please prefer using python3.8, since we have developed and tested it mostly on v3.8. Also did you check installing Python3.8 just to be sure its not due to the version issue?

**Comment by Vishalsng112** [comment]
@Malkeet-dhalla, Bug due to circular import is fixed in kachua v5.1.
