### ISSUE TITLE
[SBFL] removeDuplicates is extremely slow

### ISSUE THREAD

**Issue by Malkeet-dhalla** [CS639A-PAVT/BugTracker#23]
**Describe the bug**
For a large population, `removeDuplicates` is really slow. The main cause for this is 
the conversion of `act_mat` to string twice. You should use `arr_mat.tobytes()` as a key instead.

For a population of 300,  It took 123s to run SBLF. `removeDuplicates` alone took 80s.
I modified `removeDuplicates` like this:
```python
arr_bytes = act_mat.tobytes()
if arr_bytes not in D:
    D[arr_bytes] = i
```
Now it takes 43s to run.

**Screenshots**
Outputs from cProfiler
Using str (original code):
![str](https://user-images.githubusercontent.com/57011167/141463649-6d9a93e9-0b30-446d-952c-da457e4563ff.png)

Using bytes (modified code):
![bytes](https://user-images.githubusercontent.com/57011167/141463683-9e6378a8-1b52-4050-99ad-49796aa982fd.png)

**To reproduce**
```./kachua.py --SBFL ./example/sbfl1.tl --buggy ./example/sbfl1_buggy.tl -vars '[":x", ":y", ":z"]' --timeout 60 --ntests 50 --popsize 300 --cxpb 1.0 --mutpb 1.0 --ngen 100 --verbose True ```

**Desktop (please complete the following information):**
 - OS: EndeavourOs
 - Python 3.9
 - Kachua v5.0

**Comment by Vishalsng112** [comment]
Thank you for suggestion. The fix to this bug is added to released version v5.1.
