### ISSUE TITLE
issue-AI: how to access foo.tl file

### ISSUE THREAD

**Issue by mayank393** [CS639A-PAVT/BugTracker#24]
snippet from assignment
```
...The magarmach's region will be provided as a JSON file with the same name 
as the Turtle program. Eg. if the Turtle file is "foo.tl", then the magarmach's region 
will be in "foo.json"; a sample JSON file is given below...
```
in submissionAI.py the method def analyzeUsingAI(ir) does not contain any reference to json file which species the magarmach's region. Since the test case names would change we have to some how identify the name of json file.

Shouldn't the file name be an argument of the analyzeUsingAI function?

**Comment by pkalita595** [comment]
Fixed in Kachua v5.2
