### ISSUE TITLE
(Potentially) bug on giving flag to if

### ISSUE THREAD

**Issue by Miitk** [CS639A-PAVT/BugTracker#27]
**Describe the bug**
if there is giving flag to condition it report syntax error but it should run

**To Reproduce**
i think if flag is not zero it should run

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - Python3 version 3.8
 - Any other dependencies 
![Screenshot (477)](https://user-images.githubusercontent.com/92209107/142724724-f17bee77-e5d7-4ae0-8d45-f23909b7c9b1.png)

**Additional context**

**Comment by pkalita595** [comment]
"flag" should be a bool variable. You can use flag > 0 etc. Hope it helps.

**Comment by Miitk** [comment]
in other programming languages it gives output.

**Comment by skmuduli92** [comment]
Kachua doesn't support this at the moment. IF statement condition takes strictly a conditional expression. 
If you wan to do `if :flag` then just write `if :flag != 0` .
