### ISSUE TITLE
Unconditional jumps not happening during execution

### ISSUE THREAD

**Issue by k-k-d** [CS639A-PAVT/BugTracker#3]
**Describe the bug**

With a very simple turtle program (provided below), modifying the relative sequence number of a command manually does not result in an unconditional jump during execution. The intended behaviour is described as follows (from Assignment 2 problem stmt).

\<sequence number\>\<other than condition stmt\> \[\<relative seq number\>\]
(Other than conditional statements) For all other statements, PC is modified after execution of each statement by adding relative seq number to PC.

But in the following case, with a move command with a relative sequence number larger than 1, the PC still increments by 1 only.

The reason could be that in the ConcreteInterpreter class, all the handler functions return 1 by default except for handleCondition().

**To Reproduce**
Steps to reproduce the behaviour:
- Turtle program
```
forward 10
forward 20
forward 30
forward 40
forward 50
forward 60
```
- submission.py
```
def optimize(ir):
    ir[0] = (ir[0][0], 5)
    return ir
```
Now, execute the turtle program using the -O and -r options.

**Screenshots**
![Screenshot from 2021-09-18 03-22-58](https://user-images.githubusercontent.com/45384743/133857596-c79ef748-15ed-4806-ba9c-fdca3c5c32c8.png)

**Desktop**
 - OS: Ubuntu 20.04
 - Python3 version: Python 3.8.10

**Comment by mayanksolanki393** [comment]
@k-k-d The interpreter works a little differently.

The relative index is only used when the statement evaluates as false. Otherwise, the interpreter uses +1 as the relative index.

For what you are trying to achieve try it the following way

```
<forward 10, 1>
<False, 5> #add this
<forward 20, 1>
<forward 30, 1>
```

**Comment by k-k-d** [comment]
@mayanksolanki393 Thanks for the response.
Yes, this is the workaround I am using as well. But I wanted to confirm whether the current behaviour of the interpreter is the intended behaviour.
Also, since all the non-conditional statements always tend to have 1 as the relative jump number anyways, would it not be better to jump according to this number, rather than make no use of this field? The handler functions for all types of statements in the interpreter have the jump number available to them as arguments. It would just be a matter of returning this number instead of returning 1 by default.
