### ISSUE TITLE
Assignment 1 PAVT: Functions are not getting called

### ISSUE THREAD

**Issue by DrashtantSinghRathod** [CS639A-PAVT/BugTracker#31]
The worklist algorithm is getting called but the transfer function, meet function and initialize inside the forward analysis are not executing or not getting called. Could you please help me with this? I tried for 2days but couldnt find a solution. I placed some print statements in these function and they are not running so what could be the possible solution. 
Thank you

**Comment by pkalita595** [comment]
Can you please provide a screenshot or detailed log of your issue, as in my case, they are getting executed.

**Comment by pkalita595** [comment]
Can you please provide a screenshot or detailed log of your issue, as in my case, they are getting executed.

**Comment by DrashtantSinghRathod** [comment]
![IMG_20220911_113155](https://user-images.githubusercontent.com/74375151/189514750-2f25a223-b11e-4bd0-bcdf-7435752cd96c.jpg)
![IMG_20220911_113433](https://user-images.githubusercontent.com/74375151/189514754-80777660-fe80-40e5-8a92-e1fdae19fdc6.jpg)



I have added print stmt in initiailize function but it's not getting in the output.

**Comment by pkalita595** [comment]
Can you please let us know which files you have modified, as, on our end, it is working just fine. Are you using python version 3.8 or higher?

**Comment by DrashtantSinghRathod** [comment]
Version is python 3.10.4

**Comment by DrashtantSinghRathod** [comment]
What should I do.. Please provide me some help

**Comment by pkalita595** [comment]
Can you please come to KD 109 ASAP.

**Comment by DrashtantSinghRathod** [comment]
Ohk  , I'm on my way

**Comment by pkalita595** [comment]
He was not using the recent version of Kachua-framework. We fixed the issue.
