### ISSUE TITLE
NameError in irgen.py

### ISSUE THREAD

**Issue by Harsh30199** [CS639A-PAVT/BugTracker#4]
**Describe the bug**
Missing import pickle in irgen.py

**To Reproduce**
Just try to use run    . /kachua.py -O ./example/test.tl without  any optimisation done on ir. It will generate the bug

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python 3.9
 - Any other dependencies 

**Additional context**

**Comment by lahiri-phdworks** [comment]
This bug has been fixed and updated version released.
