### ISSUE TITLE
Conditional jumps get updated after adding instruction just after repeat ends

### ISSUE THREAD

**Issue by Varun2201** [CS639A-PAVT/BugTracker#5]
**Describe the bug**
After adding any instruction using addInstruction just after the loop ends the loop conditional jump get updated 
The conditional jump always point to same instruction after the loop not the one which are added.

**To Reproduce**
forward 20
repeat 2[
    forward 20
]
forward 20

for this program trying to add instruction in IR :
addInstruction(ir, kachuaAST.AssignmentCommand(':ok_temp',0),6)
addInstruction(ir, kachuaAST.AssignmentCommand(':ok_temp',0),6)
addInstruction(ir, kachuaAST.AssignmentCommand(':ok_temp',0),6)
addInstruction(ir, kachuaAST.AssignmentCommand(':ok_temp',0),6)

**Screenshots**
![image](https://user-images.githubusercontent.com/43462845/134295113-a4ee2551-1e63-49d2-a948-bae76f5c0341.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux 21.0.0
 - Python3 version 3.9.7
 - Any other dependencies 

**Additional context**

**Comment by lahiri-phdworks** [comment]
The output should be as shown below if I am not wrong.
```bash
Kachua v2.0.4
------------
forward 20
repeat 2[
    forward 20
]
forward 20
========== IR ==========

0 forward 20  [ 1 ]
1 :__rep_counter_1 = 2  [ 1 ]
2 (:__rep_counter_1 != 0)  [ 4 ]
3 forward 20  [ 1 ]
4 :__rep_counter_1 = (:__rep_counter_1 - 1)  [ 1 ]
5 False  [ -3 ]
6 :ok_temp = 0  [ 1 ]
7 :ok_temp = 0  [ 1 ]
8 :ok_temp = 0  [ 1 ]
9 :ok_temp = 0  [ 1 ]
10 forward 20  [ 1 ]
```. 

Can you change the line in `def updateJump( )` function from `if tgt > 0 and index + tgt >= pos:` to `if tgt > 0 and index + tgt > pos:` ? Check if that works fine.

**Comment by Varun2201** [comment]
@lahiri-phdworks Thank you! It works fine now

**Comment by lahiri-phdworks** [comment]
Do check for some other assignments. I think it must work fine. Thanks for the issue.
