### ISSUE TITLE
Wrong coverage values

### ISSUE THREAD

**Issue by Malkeet-dhalla** [CS639A-PAVT/BugTracker#6]
**Describe the bug**
The coverage values for an input calculated in `Executor.execute` are wrong. Instead of adding the current statement executed, it adds the next statement to be executed.

**To Reproduce**

ex.tl
```
if :x > 10 [
	forward 10
] else [
	forward 20
]
```
`./kachua.py -t 3 --fuzz ex.tl -d '{":x": 9}'`

Expected coverage: `[0, 3]`
Actual coverage: `[3, 4]`

**Screenshots**

![coverage_bug_ann](https://user-images.githubusercontent.com/57011167/134716803-92e41fc7-f5e5-4c67-add8-dc5a469c73e1.png)

**Desktop**
 - OS: Ubuntu 20.04
 - Python 3.8
 - Kachua 2.0.5

**Comment by lahiri-phdworks** [comment]
We have fixed this in the release. Thanks for informing. The last entry in the List is to ignored if the program terminated successfully.
