### ISSUE TITLE
About curr_metric and total_metric

### ISSUE THREAD

**Issue by Malkeet-dhalla** [CS639A-PAVT/BugTracker#7]
From what I understand `CoverageMetric.curr_metric` is the coverage of the current input and `CoverageMetric.total_metric` should be the union of coverages of previous inputs, but  `CoverageMetric.total_metric` is assigned the last improved coverage in `fuzzMain`. Is this the intended behavior or a bug?

**Comment by lahiri-phdworks** [comment]
You need to update that in the coverage function. The previous coverage function had to return the complete coverage in the `CoverageMetric.curr_metric` and that would automatically update the ` CoverageMetric.total_metric`. We will fix this.

**Comment by lahiri-phdworks** [comment]
You can now implement `def updateTotalCoverage(self, curr_metric, total_metric):` function and use it accordingly. Whatever is returned by this function is what the total metric gets updated to.
