### ISSUE TITLE
Fuzzer stops once it finds a non-improved coverage

### ISSUE THREAD

**Issue by Malkeet-dhalla** [CS639A-PAVT/BugTracker#8]
**Describe the bug**
Because of the way the loop in `fuzzMain` is written, the loop terminates when no new element is appended to the `corpus` in line 130 of `fuzzer.py`
An unlucky mutation should not cause the fuzzer to terminate and the fuzzer should continue to try different inputs.

One solution I could think of is to loop until the whole program is covered (or the time runs out) and allow picking the inputs more than once so they can be mutated multiple times.

Also, modifying `input_data.data` in `mutate` also modifies the original input, so it should be passed as a deepcopy or at least should be mentioned in `mutate`.

**Desktop :**
 - OS: Ubuntu 20.014
 - Python 3.8
 - Kachua 2.0.6

**Comment by Malkeet-dhalla** [comment]
Also, line 110 in `fuzzer.py` is redundant since `inputs` always refers to the user-provided input or the `mutated_input` added in the previous iteration.

**Comment by lahiri-phdworks** [comment]
- the input id is changed on coverage improvement. that makes the input interesting. 
- the mutation must be interesting else not added to the input list.

**Comment by lahiri-phdworks** [comment]
We can convert Line 105 to `while(true)` but it even with the current setting it will work. The mutation operator needs to be coded in that way.

**Comment by Malkeet-dhalla** [comment]
The input list grows as long as the mutation is interesting, but if the mutator returns a non-interesting input, the fuzzer ends, since the input list gets exhausted. Note how `inputs` always refer to the last element of `corpus`.

**Comment by lahiri-phdworks** [comment]
That is what must happen in a fuzzer but I agree that your suggestion also works out well for the fuzzer. Picking exactly the same input (same data input) but the mutation not being interesting (not mutating it to produce a better coverage input) is not useful. I have made the changes and released a newer version with the `while(true)` case.

**Comment by Malkeet-dhalla** [comment]
I am assuming that mutation is random and calling mutate multiple times will give different results.

**Comment by lahiri-phdworks** [comment]
But it may or may not be interesting. So implementing the mutation operator is harder when the mutation is to be done to improve coverage.

**Comment by lahiri-phdworks** [comment]
v2.1

**Comment by Malkeet-dhalla** [comment]
Instead of `while(true)` writing condition something like `while set(coverageInfo.total_metric) != set(range(len(ir))` will terminate the loop one all statements are covered.

**Comment by Malkeet-dhalla** [comment]
![fuzz_bug](https://user-images.githubusercontent.com/57011167/134776159-0278f7dd-414f-4fde-b405-ba85d94ce5d6.png)
modifying input data directly changes other inputs. Notice how input 0 and input 1 are the same.

**Comment by lahiri-phdworks** [comment]
That condition may not work well on large programs and some corner cases since fuzzing may not be able to cover some statements. The generic is `while(true)` since it will always work and the timeout makes fuzzer terminate properly.

**Comment by lahiri-phdworks** [comment]
> ![fuzz_bug](https://user-images.githubusercontent.com/57011167/134776159-0278f7dd-414f-4fde-b405-ba85d94ce5d6.png)
> modifying input data directly changes other inputs. Notice how input 0 and input 1 are the same.

Yes I agree but it doesn't cause a problem for the fuzzer to function. I agree that deepcopy must be used (as released now) since the summary of input data list is more consistent.

**Comment by Malkeet-dhalla** [comment]
Of course, that condition will be used alongside timeout, it just terminates early on in some cases but yeah, `while True` is simpler and faster.
