### ISSUE TITLE
Timeout is in minutes instead of seconds

### ISSUE THREAD

**Issue by Malkeet-dhalla** [CS639A-PAVT/BugTracker#9]
**Describe the bug**
Line 102 in `fuzzer.py` should be `end_time = time.time() + timeLimit`

**Desktop**
 - OS: Ubuntu 20.04
 - Python 3.8
 - Kachua 2.1

**Comment by lahiri-phdworks** [comment]
`timeLimit` is in minutes so we multiply by 60 to get seconds

**Comment by Malkeet-dhalla** [comment]
`./kachua.py --help` says timeout is in secs. It is fine either way.

**Comment by lahiri-phdworks** [comment]
I see. we can make it seconds then.
